CREATE TABLE PAISES(
	CODIGO_PAÍS		               VARCHAR(5)		NOT NULL,
	NOME				           VARCHAR(20)	    NOT NULL,
	TOTAL_MEDALHAS_OURO	           INT              DEFAULT 0,
	TOTAL_MEDALHAS_PRATA	       INT			    DEFAULT 0,
	TOTAL_MEDALHAS_BRONZE	       INT			    DEFAULT 0,

CONSTRAINT PAISPK
	PRIMARY KEY (CODIGO_PAIS)
);
	

CREATE TABLE MEDALHISTAS(
	NOME					    VARCHAR(20)	            NOT NULL,
	MODALIDADE_ESPORTIVA	    VARCHAR(7)	            NOT NULL,
	MEDALHA_OBTIDA		        VARCHAR(6)	            NOT NULL,

CONSTRAINT MEDALPK
	PRIMARY KEY (NOME, MODALIDE_ESPORTIVA)
);

CREATE TABLE RECORDISTAS(
	NOME				           VARCHAR(20)	            NOT NULL,
	MODALIDADE_ESPORTIVA           VARCHAR(7)	            NOT NULL,
	MODALIDADE			           INTEGER 		            NOT NULL,
	TEMPO				           DECIMAL		            NOT NULL,

CONSTRAINT RECORDPK
	PRIMARY KEY (NOME, MODALIDADE)
);


CREATE TABLE OLIMPIADAS(
	ANO	              YEAR	              NOT NULL,
	PAÍS              VARCHAR(20)         NOT NULL,
	CIDADE            VARCHAR(20) 	      NOT NULL,
	
CONSTRAINT OLIMPIADAPK
	PRIMARY KEY (ANO)
);


CREATE TABLE ESTADIOS(
	NOME	                       VARCHAR(20)	          NOT NULL,
	ENDEREÇO                       VARCHAR(20)            NOT NULL,
	CAPACIDADE                     VARCHAR(20),	 	

CONSTRAINT ESTADIOPK
	PRIMARY KEY (NOME)
);


CREATE TABLE JOGOS(
    DATA_JOGO	             DATE	                  NOT NULL,
	HORARIO_JOGO             TIME                     NOT NULL,
	MODALIDADE               VARCHAR(6)               NOT NULL,
	FASE 	 	             VARCHAR(7)               NOT NULL,
	NOME_ESTADIO             VARCHAR(20)              NOT NULL,

CONSTRAINT JOGOPK
	PRIMARY KEY (DATA_JOGO, HORARIO_JOGO,MODALIDADE, FASE),

CONSTRAINT ESTNOMEJGFK
	FOREIGN KEY (NOME_ESTADIO)  REFERENCES ESTADIO (NOME)
		ON DELETE RESTRICT ON UPDATE CASCADE
	
);

CREATE TABLE PROVAS(
	DATA_PROVA	              DATE	                 NOT NULL,
	HORARIO_PROVA             TIME                   NOT NULL,
	MODALIDADE                INTEGER                    NOT NULL,
	FASE 	 	              VARCHAR(13)              		 NOT NULL,
	RECORDE_ANTERIOR          DECIMAL,         
	NOME_ESTADIO              VARCHAR(20)             NOT NULL,      
CHECK(MODALIDADE>99 AND MODALIDADE<118),
CHECK (FASE='ELIMINATORIA' OR FASE='SEMIFINAL' OR FASE='FINAL'),       
CONSTRAINT PROVAPK
	PRIMARY KEY (DATA_PROVA, HORARIO_PROVA,  MODALIDADE, FASE),

CONSTRAINT ESTNOMEPVFK
	FOREIGN KEY (NOME_ESTADIO)  REFERENCES ESTADIO (NOME)
		ON DELETE RESTRICT ON UPDATE CASCADE
 
);

CREATE TABLE EQUIPES(
	CODIGO_EQUIPE	            VARCHAR(5)	                 NOT NULL,
	CODIGO_PAIS                 VARCHAR(5)                   NOT NULL,
	MODALIDADE_ESPORTIVA        VARCHAR(7)                   NOT NULL,
	CATEGORIA 	 	            VARCHAR(3)                   NOT NULL,
	OURO                        INTEGER                      DEFAULT 0,
	PRATA                       INTEGER                      DEFAULT 0,
	BRONZE                      INTEGER                      DEFAULT 0,

CONSTRAINT EQUIPEPK
	PRIMARY KEY (CODIGO_EQUIPE),

CONSTRAINT PAISEQFK
	FOREIGN  KEY (CODIGO_PAIS) REFERENCES PAISES(CODIGO_PAIS)
		ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE ATLETAS(
	NUM_INSCRICAO               INTEGER		    NOT NULL,
	NOME             			VARCHAR(50)     NOT NULL,
	DATA_NASCIMENTO      		DATE 			NOT NULL,
	PESO					    DECIMAL(4,2)	NOT NULL,
	ALTURA				        DECIMAL(1,2)    NOT NULL,
	SEXO					    CHAR 		    NOT NULL,
	TOTAL_MEDALHAS_OURO	        INTEGER		    DEFAULT 0,
	TOTAL_MEDALHAS_PRATA	    INTEGER		    DEFAULT 0,	
    TOTAL_MEDALHAS_BRONZE	    INTEGER		    DEFAULT 0,	
    CODIGO_EQUIPE			    VARCHAR(5) 		NOT NULL,
	CODIGO_PAIS			        VARCHAR(5)		NOT NULL,
	ANO_OLIMPIADAS			    YEAR 			NOT NULL,
	
CONSTRAINT ATLETPK
	PRIMARY KEY (NUM_INSCRICAO),

CONSTRAINT  ATLETEQPFK
	FOREIGN KEY (CODIGO_EQUIPE) REFERENCES EQUIPES(CODIGO_EQUIPE)
		ON DELETE SET NULL ON UPDATE	    CASCADE,

CONSTRAINT ATLETPAISFK
	FOREIGN KEY (CODIGO_PAIS) REFERENCES PAISES(CODIGO_PAIS)
		ON DELETE RESTRICT ON UPDATE	  CASCADE,

CONSTRAINT ATLETOLIMPFK
	FOREIGN KEY (ANO_OLIMPIADAS) REFERENCES OLIMPIADAS (ANO)
		ON DELETE RESTRICT	ON UPDATE	CASCADE

);

CREATE TABLE JUIZES(
	NUM_INSCRICAO		INTEGER		NOT NULL,
	NOME				VARCHAR(50)	NOT NULL,
	DATA_NASCIMENTO	DATE			NOT NULL,
	NACIONALIDADE		VARCHAR(20)	NOT NULL,
	
	CONSTRAINT JUIZPK
			PRIMARY KEY (NUM_INSCRICAO)
);

CREATE TABLE PARTICIPA_DE(
	ANO                  YEAR	           NOT NULL,
	CODIGO_PAIS          VARCHAR(5)          NOT NULL,
	
CONSTRAINT PARTCPK
	PRIMARY KEY (ANO, CODIGO_PAIS),

CONSTRAINT PTCANOPAISFK
	FOREIGN  KEY (CODIGO_PAIS) REFERENCES PAISES(CODIGO_PAIS)
		ON DELETE RESTRICT ON UPDATE CASCADE,

CONSTRAINT PTANOFK
	FOREIGN  KEY (ANO) REFERENCES OLIMPIADAS (ANO)
		ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE POSSUI_R(
	NOME			VARCHAR(20)	    NOT NULL,
	MODALIDADE	    INTEGER 		NOT NULL,
	ANO	            YEAR	        NOT NULL,

CONSTRAINT	POSRPK
		PRIMARY KEY (NOME, ANO),

CONSTRAINT POSRECNFK
	FOREIGN KEY (NOME) REFERENCES RECORDISTAS(NOME)
		ON DELETE CASCADE	ON UPDATE CASCADE,

CONSTRAINT POSRRECMFK
	FOREIGN KEY (MODALIDADE) REFERENCES RECORDISTAS(MODALIDADE)
		ON DELETE RESTRICT	ON UPDATE CASCADE,

CONSTRAINT POSROLIMPFK
	FOREIGN KEY	(ANO) REFERENCES OLIMPIADAS (ANO)
		ON DELETE RESTRICT ON UPDATE CASCADE
	
);

CREATE TABLE POSSUI_M(
	NOME					VARCHAR(20)          	NOT NULL,
	MODALIDADE_ESPORTIVA	VARCHAR(7)	            NOT NULL,
	ANO	              	    YEAR	            	NOT NULL,

	CONSTRAINT	POSMPK
		PRIMARY KEY (NOME, ANO),

	CONSTRAINT POSMMEDFK
		FOREIGN KEY (NOME) REFERENCES MEDALHISTAS(NOME)
			ON DELETE CASCADE	ON UPDATE CASCADE,

CONSTRAINT POSMMODFK
		FOREIGN KEY (MODALIDADE_ESPORTIVA) REFERENCES MEDALHISTAS(MODALIDADE_ESPORTIVA)
			ON DELETE RESTRICT ON UPDATE CASCADE,

CONSTRAINT POSROLIMPFK
	FOREIGN KEY	(ANO) REFERENCES OLIMPIADAS (ANO)
		ON DELETE RESTRICT ON UPDATE CASCADE
);


CREATE TABLE PARTICIPA_JOGOS_EQUIPES(
	CODIGO_EQUIPE	       VARCHAR(5)	            NOT NULL,
	JUIZ			       INTEGER	        		NOT NULL,
	DATA_JOGO	           DATE	                    NOT NULL,
	HORARIO_JOGO           TIME                     NOT NULL,
	MODALIDADE             INTEGER              		NOT NULL,
	FASE 	 	           VARCHAR(7)              		NOT NULL,
	RESULTADO 	           VARCHAR(7)                    NOT NULL,
	PENALIDADES 	       VARCHAR(30)                
CHECK(MODALIDADE>99 AND MODALIDADE<118),
CHECK (FASE='GRUPOS' OR FASE='OITAVAS' OR FASE='QUARTAS' OR FASE='SEMIFINAL' OR FASE='FINAL'),
CONSTRAINT PARJOEQPK
	PRIMARY KEY (CODIGO_EQUIPE, MODALIDADE, DATA_JOGO, HORARIO_JOGO, FASE),

CONSTRAINT PARJOEQEQPFK
	FOREIGN KEY (CODIGO_EQUIPE) REFERENCES EQUIPES(CODIGO_EQUIPE)
		ON DELETE RESTRICT ON UPDATE CASCADE,

CONSTRAINT PARJOEQJUIZFK
	FOREIGN KEY (JUIZ) REFERENCES JUIZES(NUM_INSCRICAO)
		ON DELETE RESTRICT ON UPDATE CASCADE,

CONSTRAINT PARJOEQDATJOGFK
	FOREIGN KEY (DATA_JOGO) REFERENCES JOGOS(DATA_JOGO)
		ON DELETE RESTRICT ON UPDATE CASCADE,

CONSTRAINT PARJOEQHORJOGFK
	FOREIGN KEY (HORARIO_JOGO) REFERENCES JOGOS(HORARIO_JOGO)
		ON DELETE RESTRICT ON UPDATE CASCADE,

CONSTRAINT PARJOEQMODJOGFK
	FOREIGN KEY (MODALIDADE) REFERENCES JOGOS(MODALIDADE)
		ON DELETE RESTRICT ON UPDATE CASCADE,

CONSTRAINT PARJOEQFASJOGFK
	FOREIGN KEY (FASE) REFERENCES JOGOS(FASE)
		ON DELETE RESTRICT ON UPDATE CASCADE
);


CREATE TABLE PARTICIPA_PROVAS_EQUIPES(
	CODIGO_EQUIPE		VARCHAR(5)		    NOT NULL,
	JUIZ				INTEGER		        NOT NULL,
	DATA_PROVA 		    DATE			    NOT NULL,
	HORARIO_PROVA 		TIME			    NOT NULL,
	MODALIDADE 		    INTEGER			        NOT NULL,
	FASE  				VARCHAR(13)			        NOT NULL,
	TEMPO 		        DECIMAL(4,3)        NOT NULL,
	RESULTADO  		    VARCHAR(20)	        NOT NULL,
	RECORDE			    DECIMAL(4,3),		
	PENALIDADES		    VARCHAR(30),	
CHECK(MODALIDADE>99 AND MODALIDADE<118),
CHECK (FASE='ELIMINATORIA' OR FASE='SEMIFINAL' OR FASE='FINAL'), 
	CONSTRAINT PARPREQPK
		PRIMARY KEY (CODIGO_EQUIPE, MODALIDADE, DATA_PROVA, HORARIO_PROVA, FASE),
	
	CONSTRAINT PARPREQFK
		FOREIGN KEY (CODIGO_EQUIPE) REFERENCES EQUIPES (CODIGO_EQUIPE)
			ON DELETE RESTRICT ON UPDATE CASCADE,
	
	CONSTRAINT PARPREQJUIZFK
		FOREIGN KEY (JUIZ) REFERENCES JUIZES(NUM_INSCRICAO)
			ON DELETE RESTRICT ON UPDATE CASCADE,

	CONSTRAINT PARPREQDATPRFK
		FOREIGN KEY (DATA_PROVA) REFERENCES PROVAS(DATA_PROVA)
			ON DELETE RESTRICT ON UPDATE CASCADE,

	CONSTRAINT PARPREQHRPRFK
		FOREIGN KEY (HORARIO_PROVA) REFERENCES PROVAS(HORARIO_PROVA)
			ON DELETE RESTRICT ON UPDATE CASCADE,

	CONSTRAINT PARPREQMODPRFK
		FOREIGN KEY (MODALIDADE) REFERENCES JOGOS(MODALIDADE)
			ON DELETE RESTRICT ON UPDATE CASCADE,	

	CONSTRAINT PARPREQFASPRFK
		FOREIGN KEY (FASE) REFERENCES JOGOS(FASE)
			ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE COMPETE_POR_PAIS_EM(
	ANO                  YEAR	            NOT NULL,
	CODIGO_PAIS          VARCHAR(5)         NOT NULL,
	ATLETA		         INTEGER		    NOT NULL,

	CONSTRAINT COMPPORPAISPK
	PRIMARY KEY (ANO, CODIGO_PAIS),

CONSTRAINT COMPPAISANOFK
	FOREIGN KEY (ANO) REFERENCES OLIMPIADAS (ANO)
			ON DELETE RESTRICT ON UPDATE CASCADE,

CONSTRAINT COMPPAISCODFK
	FOREIGN	KEY (CODIGO_PAIS) REFERENCES PAISES(CODIGO_PAIS)
			ON DELETE CASCADE ON UPDATE CASCADE,

CONSTRAINT COMPPAISATLFK
	FOREIGN KEY (ATLETA) REFERENCES ATLETAS(NUM_INSCRICAO)
			ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PARTICIPA_PROVAS_ATLETAS(
	ATLETA			INTEGER		    NOT NULL,
	JUIZ			INTEGER		    NOT NULL,
	DATA_PROVA		DATE			NOT NULL,
	HORARIO_PROVA	TIME			NOT NULL,
	MODALIDADE		INTEGER			    NOT NULL,
	FASE			VARCHAR(13)			    NOT NULL,
	TEMPO			DECIMAL(4,3)	NOT NULL,
	RESULTADO		VARCHAR(20)     NOT NULL,
	RECORDE			DECIMAL(4,3),
	PENALIDADES		VARCHAR(30),
CHECK(MODALIDADE>99 AND MODALIDADE<118),
CHECK (FASE='ELIMINATORIA' OR FASE='SEMIFINAL' OR FASE='FINAL'), 
	CONSTRAINT  PARTPROVATLPK
		PRIMARY KEY (ATLETA, DATA_PROVA, HORARIO_PROVA, MODALIDADE, FASE),
	
CONSTRAINT PARTPROVATLPRVJFK
		FOREIGN KEY (ATLETA) REFERENCES ATLETAS (NUM_INSCRICAO) ON DELETE RESTRICT ON UPDATE CASCADE,

	CONSTRAINT PARTPROVATLPRVJFK
		FOREIGN KEY (JUIZ) REFERENCES JUIZES(NUM_INSCRICAO)
			ON DELETE RESTRICT ON UPDATE CASCADE,

	CONSTRAINT PARTPROVAATLPRVDTFK
		FOREIGN KEY (DATA_PROVA) REFERENCES PROVAS(DATA_PROVA)
			ON DELETE RESTRICT ON UPDATE CASCADE,

	CONSTRAINT PARPROVAATLPRVHORFK
		FOREIGN KEY (HORARIO_PROVA) REFERENCES PROVAS(HORARIO_PROVA)
			ON DELETE RESTRICT ON UPDATE CASCADE,
	
	CONSTRAINT PARPROVAATLPRVMODFK
		FOREIGN KEY (MODALIDADE) REFERENCES PROVAS(MODALIDADE)
			ON DELETE RESTRICT ON UPDATE CASCADE,

	CONSTRAINT PARPROVAATLPRVFASFK
		FOREIGN KEY(FASE) REFERENCES PROVAS(FASE)
			ON DELETE RESTRICT ON UPDATE CASCADE
);